/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2021-05-11 14:33:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sch.pkg.*;
import java.util.*;
import java.lang.*;
import com.jcraft.jsch.*;
import org.apache.poi.*;
import java.sql.*;
import com.Ostermiller.util.*;

public final class CreateNew_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("com.Ostermiller.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.sch.pkg");
    _jspx_imports_packages.add("org.apache.poi");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.jcraft.jsch");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Schedular- QA</title>\r\n");
      out.write("<link rel =\"stylesheet\" href=\"CSS/indexStyle.css\">\r\n");
      out.write("<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(window).load(function() {\r\n");
      out.write("\t$(\".loader\").fadeOut(\"slow\");\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("            function validate()\r\n");
      out.write("            {\r\n");
      out.write("            \tvar date = document.getElementById(\"filedate\");\r\n");
      out.write("                var NumNotice = document.getElementById(\"NumNotice\");\r\n");
      out.write("                \r\n");
      out.write("                var valid = true;\r\n");
      out.write("                if(date.value.length<=0 ||NumNotice.value.length<=0)\r\n");
      out.write("                    {\r\n");
      out.write("                        alert(\"Please fill all fields\");\r\n");
      out.write("                        valid = false;\r\n");
      out.write("                    }\r\n");
      out.write("                \r\n");
      out.write("                else{\r\n");
      out.write("                    if(isNaN(NumNotice.value)){\r\n");
      out.write("                        alert(\"Please enter number only\");\r\n");
      out.write("                valid = false;}\r\n");
      out.write("            }\r\n");
      out.write("                 \r\n");
      out.write("                return valid;\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("<script>\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("  function setOptions(value) \r\n");
      out.write("  {\r\n");
      out.write("\t  if(value==\"GSP\" || value == \"SJTA\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\t  console.log(\"4 violations\"+value);\r\n");
      out.write("\t\t  document.getElementById(\"5\").style.display = \"none\";\r\n");
      out.write("\t\t  document.getElementById(\"ACM\").style.display = \"Block\";\r\n");
      out.write("\t\t  \r\n");
      out.write("\t}\t\r\n");
      out.write("\t  else if (value == \"CAPEMAY\")\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t\t  console.log(\"4 violations\"+value);\r\n");
      out.write("\t\t  document.getElementById(\"5\").style.display = \"none\";\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  }\r\n");
      out.write("\t  else\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t  console.log(\"5 violations\"+value);\r\n");
      out.write("\t\t  document.getElementById(\"5\").style.display = \"Block\";\t\t  \r\n");
      out.write("\t\t  document.getElementById(\"ACM\").style.display = \"none\";\r\n");
      out.write("\t\t}  \r\n");
      out.write("\t  \r\n");
      out.write("  }\r\n");
      out.write("      \r\n");
      out.write("    </script>\r\n");
      out.write("        \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"loader\"></div>\r\n");
      out.write("<div id=\"left\"></div>\r\n");
      out.write("<div id=\"right\"></div>\r\n");
      out.write("<div id=\"top\"></div>\r\n");
      out.write("<div id=\"bottom\"></div>\r\n");
      out.write("<div class=\"stitched\">\r\n");
      out.write("<h1>Create New Set</h1>\r\n");
      out.write("</div>\r\n");
      out.write("<center><img src='IMG/statusNULL.png' ></img></center>\r\n");
      out.write("<nav>\r\n");
      out.write("  <ul class=\"top-menu\">\r\n");
      out.write("    <li><a href=\"index.jsp\">Home</a><div class=\"menu-item\" id=\"home\"></div></li>\r\n");
      out.write("    <li><a href=\"CreateNew.jsp\">Create New Set</a><div class=\"menu-item\" id=\"CreateNew\"></div></li>\r\n");
      out.write("    <li><a href=\"ExistingViolations.jsp\">OpenExisting</a><div class=\"menu-item\" id=\"OpenExisting\"></div></li>\r\n");
      out.write("    <li><a href=\"contact.jsp\">Contact</a><div class=\"menu-item\" id=\"contact\"></div></li>\r\n");
      out.write("    <li><a href=\"about.jsp\">About</a><div class=\"menu-item\" id=\"About\"></div></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</nav><br>\r\n");
      out.write("\r\n");
      out.write("<form font-size=\"75px;\" action =\"ConfirmDetails.jsp\" name=\"myform\" post\" onsubmit=\"return validate()\">\r\n");
      out.write("<p>Please enter File date and transaction date within 60 days otherwise the notice will not be created</p>\r\n");
      out.write("\r\n");
      out.write("<table style=\"width:30%\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td><whi/>DB :</td>\r\n");
      out.write("<td align=\"left\">\r\n");
      out.write("    <select name = \"DB\" id =\"DB\" onchange=\"setOptions(this.value)\">\r\n");
      out.write("  <option value=\"NJP2TST\">NJP2TST</option>\r\n");
      out.write("  <option value=\"njrbtst\">NJRBTST</option>\r\n");
      out.write("  <option value=\"NJAETTST\">NJAETTST</option>\r\n");
      out.write("</select></td>  \r\n");
      out.write("</tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><whi/>Agency :</td>\r\n");
      out.write("    <td align=\"left\">\r\n");
      out.write("    <select name = \"agencyid\" id =\"agencyid\" onchange=\"setOptions(this.value)\">\r\n");
      out.write("  <option value=\"NJTP\">NJTP</option>\r\n");
      out.write("  <option value=\"GSP\">GSP</option>\r\n");
      out.write("  <option value=\"DRJ\">DRJ</option>\r\n");
      out.write("  <option value=\"DRJAET\">DRJAET</option>\r\n");
      out.write("   <option value=\"DRBA\">DRBA</option>\r\n");
      out.write("    <option value=\"DRPA\">DRPA</option>\r\n");
      out.write("     <option value=\"SJTA\">SJTA</option>\r\n");
      out.write("     <option value=\"CAPEMAY\">CAPEMAY</option>\r\n");
      out.write("</select></td>  \r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><whi/>File Date :</td>\r\n");
      out.write("    <td align=\"left\"><input type =\"date\" id =\"filedate\" name =\"filedate\"/></td> \r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><whi/>Transaction Date :</td>\r\n");
      out.write("    <td align=\"left\"><input type =\"date\" id =\"trxDate\" name =\"trxDate\"/></td> \r\n");
      out.write("  </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td><whi/>Normal or ACM</td>\r\n");
      out.write("    <td align=\"left\">\r\n");
      out.write("    <select name = \"ViolType\" id= \"ViolType\">\r\n");
      out.write("    <option value=\"NOR\">NORMAL</option>\r\n");
      out.write("    <option value=\"ACM\" id =\"ACM\">ACM</option>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("  <td><whi/>Number of notices :</td>\r\n");
      out.write("    <td align=\"left\">\r\n");
      out.write("    <select name = \"NumNotice\" id= \"NumNotice\">\r\n");
      out.write("  <option value=\"1\">1</option>\r\n");
      out.write("  <option value=\"2\">2</option>\r\n");
      out.write("  <option value=\"3\">3</option>\r\n");
      out.write("  <option value=\"4\">4</option>\r\n");
      out.write("  <option value=\"5\">5</option>\r\n");
      out.write("  <option value=\"6\">6</option>\r\n");
      out.write("  <option value=\"7\">7</option>\r\n");
      out.write("  <option value=\"8\">8</option>\r\n");
      out.write("  <option value=\"9\">9</option>\r\n");
      out.write("  <option value=\"10\">10</option>\r\n");
      out.write("  <option value=\"20\">20</option>\r\n");
      out.write("  <option value=\"50\">50</option>\r\n");
      out.write("  \r\n");
      out.write("</select></td>  \r\n");
      out.write("      </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><whi/>Number of violations per notice : </td>\r\n");
      out.write("    <td align=\"left\">\r\n");
      out.write("    <select name = \"violnumber\" id= \"violnumber\">\r\n");
      out.write("  <option value=\"1\" id =\"1\">1</option>\r\n");
      out.write("  <option value=\"2\" id =\"2\">2</option>\r\n");
      out.write("  <option value=\"3\" id =\"3\">3</option>\r\n");
      out.write("  <option value=\"4\" id= \"4\">4</option>\r\n");
      out.write("  <option value=\"5\" id=\"5\">5</option>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</select></td>  \r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<input type=\"submit\" value=\"Confirm Details\">\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
